version: '3.4'

services:
  php:
    build: ./docker
    env_file:
      - ./.env
    volumes:
      - ./:/var/www/app:rw,cached
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      # - ./:/var/www/app:rw

  nginx:
    image: nginx:1.17-alpine
    depends_on:
      - php
    volumes:
      - ./public:/var/www/app/public:ro
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  mercure:
    image: dunglas/mercure
    environment:
      - JWT_KEY=myJWTKey
      - DEMO=1
      - ALLOW_ANONYMOUS=1
      - PUBLISH_ALLOWED_ORIGINS=http://localhost:9090
      - DEBUG=1
      - CORS_ALLOWED_ORIGINS=http://localhost
    ports:
      - "9090:80"